# Generated by Django 3.0.5 on 2020-04-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200429_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='summary',
            table='summary',
        ),
    ]
